### ISSUE TITLE
Crash occurs on Android 6/5 versions

### ISSUE THREAD

**Issue by floydkim** [Survicate/react-native-survicate#30]
Hello.
Thank you for your support on React Native community.

(I'm using translator)

We would like to inform you that there is an issue reported through Firebase Crashlytics.
This error causes a crash and is presumed to occur when the app is launched.

Please patch this error or change the Android supported version policy.

The error is being reported on devices with Android OS 6 or lower.
(about 95% in Android version v6 / 5% in v5)

our `minSdkVersion` is 21. (FYI, Android 5)

Errors fall into two groups.

```
Fatal Exception: java.lang.NoClassDefFoundError: com.survicate.surveys.-$$Lambda$SynchronizationManager$SkOlxyXiD9wh97iSis0UDNQ7r6M
       at com.survicate.surveys.SynchronizationManager.sendSeenSurveys(SynchronizationManager.java:108)
       at com.survicate.surveys.SynchronizationManager.access$100(SynchronizationManager.java:31)
       at com.survicate.surveys.SynchronizationManager$1.onReceive(SynchronizationManager.java:74)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:993)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
Fatal Exception: java.lang.NoClassDefFoundError: com.survicate.surveys.-$$Lambda$SynchronizationManager$57tsmhygo-yU9NGkoJ2UGe_4p_w
       at com.survicate.surveys.SynchronizationManager.lambda$init$1$SynchronizationManager(SynchronizationManager.java:80)
       at com.survicate.surveys.-$$Lambda$SynchronizationManager$cc-EpqZz68Ml-k3XyEtoIGiV774.update(lambda)
       at com.survicate.surveys.helpers.Observable.notifyObservers(Observable.java:50)
       at com.survicate.surveys.helpers.BehaviourObservable.notifyObservers(BehaviourObservable.java:22)
       at com.survicate.surveys.PersistenceManager.lambda$initializeDataFromStore$0(PersistenceManager.java:69)
       at com.survicate.surveys.-$$Lambda$PersistenceManager$eOVJVc5AkZ-3ldWfgYVWwyXm_yM.accept(lambda)
       at com.survicate.surveys.utils.SimpleAsyncTask$1.onPostExecute(SimpleAsyncTask.java:73)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6117)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by floydkim** [comment]
using `"@survicate/react-native-survicate": "1.1.12",`

**Comment by sergey-duzhych** [comment]
Hi @floydkim thank you for reporting the issue! 
Could you please try adding the following code to your build.gradle file and see if the crash still occurs?
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by floydkim** [comment]
@sergey-duzhych 
Thank you.
I'll try it.

**Comment by floydkim** [comment]
I have a Question.

Should I add `compileOptions` to my `app/build.gradle` file?
It would be nice if we could limit the impact of the changes.

Would changing the module's build.gradle settings have the same effect?
(using `patch-package` to change `node_modules/@survicate/react-native-survicate`)

**Comment by floydkim** [comment]
It reproduced on emulator!
(The app is built with release configuration. Emulator : Android 6 AVD)

My app crashes as soon as it starts up.
Unfortunately, still crashing after adding `compileOptions`..

```
java.lang.NoClassDefFoundError: com.survicate.surveys.-$$Lambda$SynchronizationManager$SkOlxyXiD9wh97iSis0UDNQ7r6M
        at com.survicate.surveys.SynchronizationManager.sendSeenSurveys(SynchronizationManager.java:108)
        at com.survicate.surveys.SynchronizationManager.access$100(SynchronizationManager.java:31)
        at com.survicate.surveys.SynchronizationManager$1.onReceive(SynchronizationManager.java:74)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by floydkim** [comment]
I think something's wrong with Survicate Android SDK 1.6.5.

I downgraded the version of `@survicate/react-native-survicate` to `1.1.11`. (previously `1.1.12` with Android SDK 1.6.1 - [change log](https://developers.survicate.com/mobile-sdk/react-native/#1112-2022-08-04))

Then, my app runs on Android OS 6 emulator. 🎉  (with/without `compileOptions` in gradle script.)

**Comment by j-brzozowski** [comment]
@floydkim we have addressed this issue in Android SDK 1.7.0. Please update RN library to `1.1.15`.
